### ISSUE TITLE
Resolution Issue

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#1]
**Bug Description**
Screens with a resolution lesser then 1080p fail to load all contents of the extension. Take a look at the attached screenshot.

**(The following screenshot is captured on 1366x768 resolution)**

![Screenshot (899)](https://user-images.githubusercontent.com/42475986/94302282-98f4bd80-ff89-11ea-9680-981fa842a793.png)

**Expected Behaviour**
All contents of the extension should fit properly for all types of resolutions.

**Comment by yanmarex** [comment]
I going to work in this Issue.

**Comment by AmitGujar** [comment]
> I going to work in this Issue.

Sure.

**Comment by AmitGujar** [comment]
@yanmarex do you working on this?
