### ISSUE TITLE
Add Todo Section

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#12]
**Todo Section**
Add the todo section in the bottom right section.

**Features Required**
Once the task has been completed, allow the user to mark the task as completed.
Allow users to delete the todo list.

**Screenshot**
![Screenshot 2020-10-04 003856](https://user-images.githubusercontent.com/42475986/94999912-514de180-05da-11eb-82e7-41127f479133.jpg)

**Comment by MKPATH2015** [comment]
Can I work on this? :)

**Comment by AmitGujar** [comment]
Sure

**Comment by MKPATH2015** [comment]
This is the rough look of the UI

![image](https://user-images.githubusercontent.com/19207078/95020586-adbc0a00-0689-11eb-8f53-e9172eb4745a.png)

I have couple of doubts
1) Will we hold only todo list of current day? If not, do we need that ellipsis on top-right corner for every day's todo list? Or is it just for entire Todo list window?
2) What options do we have inside that ellipsis?

**Comment by AmitGujar** [comment]
We will keep todo list of the current day only, I mean, I wonder if anyone will save their weekly todo in the browser.

**Comment by AmitGujar** [comment]
In terms of UI, it looks nice.

**Comment by deepharshsri** [comment]
Can I work on this? If possible I will try to create a pop up todolist...

**Comment by AmitGujar** [comment]
sure.

**Comment by MKPATH2015** [comment]
Hey, @AmitGujar I am still working on this

**Comment by AmitGujar** [comment]
> Hey, @AmitGujar I am still working on this

yes, I know, will check his work before he makes the pull.

**Comment by deepharshsri** [comment]
Sir, I have completed the pop-up todo-list. Please assigned me again
![Screenshot (59)](https://user-images.githubusercontent.com/58383573/95179397-31870b00-07de-11eb-8fa7-6942da2c7035.png)

**Comment by AmitGujar** [comment]
@deepharshsri I am sorry but we finalized the design and the issue is almost solved.

**Comment by AmitGujar** [comment]
@MKPATH2015 try keeping todo in local storage.

**Comment by MKPATH2015** [comment]
Hey I thought of finishing the persistence this weekend. Is this addressed, already?

**Comment by AmitGujar** [comment]
> Hey I thought of finishing the persistence this weekend. Is this addressed, already?

Yeah it's finished successfully.
