### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#15]
Bug Description
Screens with a resolution lesser than 1080p fail to load all contents of the extension.

To Reproduce
Change your screen resolution less than 1080p.

Expected behavior
All contents of the extension should be optimized for all types of screen resolutions or optimize it for 1366 x 768 screens.

**Comment by M4yankChoudhary** [comment]
Can i take this ?

**Comment by AmitGujar** [comment]
Sure
