### ISSUE TITLE
Todo Feature

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#18]
**Description**
Todo feature already exists in Bink but it's not persistence. If we close the browser or tab then the todo list gets reset.

**To Reproduce**
- Add your todo on the list.
- Open a new tab and check the todo list.

**Expected behavior**
- The Todo list should not get reset until the user manually deletes even after the browser and tab close.
- When a user marks todo as completed an automatic strikethrough effect should apply for that task after mark.

**NOTE**
- Don't change the current todo design.

**Comment by MinerBigWhale** [comment]
Hello,
I can work on this.
I could implement saving of todo list in localstorage

**Comment by AmitGujar** [comment]
Sure, I will assign you. Yes, localstorage will work.
