### ISSUE TITLE
Improve text readability 

### ISSUE THREAD

**Issue by MinerBigWhale** [AmitGujar/Bink-Chrome-Extension#19]
Text is easy to read on dark photos but not on brighter photos it is not.

Improve readability by adding dark text stroke 

![image](https://user-images.githubusercontent.com/3715525/95423109-d588c780-0940-11eb-9f1e-7db88c5b3518.png)

Stroke will be unnoticable on darck background but really helpfull on bright background

**Comment by AmitGujar** [comment]
Dark text stroke looks nice on larger font but not on the small font, will add some dark shadows to the text. Users also can change the background manually if they don't like light wallpapers.

**Comment by AmitGujar** [comment]
I tried by applying some effects to text in order to make it visible in light wallpapers but it looks bad. Since this extension is getting random photos from Unsplash, there is no parameter for filer dark wallpapers, so the only solution to this is to change wallpaper manually.
