### ISSUE TITLE
Auto Change Wallpaper in specific interval of time.

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#2]
**Bug Description** 
Currently, the background image changes automatically but there is a problem. New Tab image changes automatically only if the New Blank Tab is open other then currently you are working on, if blank New Tab isn't open then the wallpaper fails to change automatically.

**Expected behavior** 
Automatically change background after 24 hours / 12 hours.

**Additional context**
This API can help.
https://developer.chrome.com/apps/alarms

**Comment by Kalovelo** [comment]
Hey @AmitGujar 👋  , could I work on this for hacktoberfest2020?

**Comment by AmitGujar** [comment]
> Hey @AmitGujar 👋  , could I work on this for hacktoberfest2020?

Sure.
