### ISSUE TITLE
Search engine Selection 

### ISSUE THREAD

**Issue by MinerBigWhale** [AmitGujar/Bink-Chrome-Extension#20]
Add a settings page to select search engine used for search bar

**_Must include default top 5 :_**
- Bing 
- Google 
- Yahoo
- Ecosia
- DuckDuck Go

**_Style of the bar must change according to the setting_**
- Logo on the button 
- Color of halo

**Comment by AmitGujar** [comment]
No more work on a search engine will be done because in upcoming days I am gonna remove it. I noticed that most people prefer to address bar rather than an extension search.

**Comment by MinerBigWhale** [comment]
That make sens 😉
