### ISSUE TITLE
Add Direct Download 

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#29]
**Description**
Download photo button redirect users to unsplash site and users have to manually click on download button in order to download photo.

**Expected**
Download photo button should allow users to direct download in same tab of extension rather than redirecting it to external site.

**Additional Context**
This will help - https://unsplash.com/documentation#track-a-photo-download

**Comment by utkarsh4321** [comment]
Hi @AmitGujar i can work on this isue.

**Comment by AmitGujar** [comment]
Sure.

**Comment by k-azadzoi** [comment]
Hi. I know someone has already been assigned to this issue. However just for fun I wanted to see if I could complete it. 

I already have a fix and ready to submit a PR for review. If the original assignee wants to submit his I'll step away. Cheers!

**Comment by AmitGujar** [comment]
> Hi. I know someone has already been assigned to this issue. However just for fun I wanted to see if I could complete it.
> 
> I already have a fix and ready to submit a PR for review. If the original assignee wants to submit his I'll step away. Cheers!

of course. don't worry it's not first-come, first-serve. You can submit PR
