### ISSUE TITLE
Replace text button to icon.

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#3]
**Description**
Change ME button allows users to change the background manually, Change that button to the Refresh/Reload icon.

![Screenshot (29)](https://user-images.githubusercontent.com/42475986/94394248-7d9cd480-017a-11eb-9b11-ebc4991089df.png)

Expected Changes - 
- Only icon (not icon + text).
- Icon background must be transparent.
- Animated icon will be appreciated.

**Comment by Abdul-Sen** [comment]
Hi! I'd like to tackle this issue as part of Hacktoberfest. Can you please assign this to me?

**Comment by AmitGujar** [comment]
> Hi! I'd like to tackle this issue as part of Hacktoberfest. Can you please assign this to me?

Sure

**Comment by vandana1499** [comment]
Hello, I would like to work on it. Please assign it to me? 
I have done it.

**Comment by ghost** [comment]
Hey Amit What if your buttons are given best animations in world, Please assign me this task for hackoctober fest!

**Comment by AmitGujar** [comment]
> Hello, I would like to work on it. Please assign it to me?
> I have done it.

create PR will review that.

**Comment by AmitGujar** [comment]
> Hey Amit What if your buttons are given best animations in world, Please assign me this task for hackoctober fest!

sure

**Comment by AmitGujar** [comment]
NOTE - Multiple peoples are assigned for this issue and because of that, I will review the work of all of you are then merge the request of best among you.
