### ISSUE TITLE
Auto Change Wallpaper

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#31]
Bug Description
Currently, background wallpaper doesn't change automatically

Expected behavior
Wallpaper should change automatically in some specific time period, even if the browser is closed.

**Comment by lucashilles** [comment]
Hello! Can i work on this issue?

**Comment by AmitGujar** [comment]
Yes

**Comment by lucashilles** [comment]
I made the changes needed, can you review?
