### ISSUE TITLE
Add top visited sites.

### ISSUE THREAD

**Issue by AmitGujar** [AmitGujar/Bink-Chrome-Extension#7]
**Description**
Replace current links in the navbar of extension to most visited sites.

**Screenshot**
![Screenshot 2020-09-30 130210](https://user-images.githubusercontent.com/42475986/94656086-3569e780-031d-11eb-9584-ae191087f6b8.jpg)

**This API will help**
https://developer.chrome.com/extensions/topSites

**Comment by nicosh** [comment]
if like  to assign me this issue I'll take a look

**Comment by AmitGujar** [comment]
Sure

**Comment by nicosh** [comment]
I will submit the PR later today so will be valid for hacktoberfest ok?

**Comment by AmitGujar** [comment]
Yes, No problem.

**Comment by AmitGujar** [comment]
@nicosh There is a problem, the Number of the top-visited sites is greater than 7, could you work on this again to make it limited to 7.
